const options = [
  {value: 'USD', label: "US Dollar"},
  {value: 'CAD', label: "Canadian Dollar"},
  {value: 'EUR', label: "Euro"},
  {value: 'AED', label: "United Arab Emirates Dirham"},
  {value: 'AFN', label: "Afghan Afghani"},
  {value: 'ALL', label: "Albanian Lek"},
  {value: 'AMD', label: "Armenian Dram"},
  {value: 'ARS', label: "Argentine Peso"},
  {value: 'AUD', label: "Australian Dollar"},
  {value: 'AZN', label: "Azerbaijani Manat"},
  {value: 'BAM', label: "Bosnia-Herzegovina Convertible Mark"},
  {value: 'BDT', label: "Bangladeshi Taka"},
  {value: 'BGN', label: "Bulgarian Lev"},
  {value: 'BHD', label: "Bahraini Dinar"},
  {value: 'BIF', label: "Burundian Franc"},
  {value: 'BND', label: "Brunei Dollar"},
  {value: 'BOB', label: "Bolivian Boliviano"},
  {value: 'BRL', label: "Brazilian Real"},
  {value: 'BWP', label: "Botswanan Pula"},
  {value: 'BYR', label: "Belarusian Ruble"},
  {value: 'BZD', label: "Belize Dollar"},
  {value: 'CDF', label: "Congolese Franc"},
  {value: 'CHF', label: "Swiss Franc"},
  {value: 'CLP', label: "Chilean Peso"},
  {value: 'CNY', label: "Chinese Yuan"},
  {value: 'COP', label: "Colombian Peso"},
  {value: 'CRC', label: "Costa Rican Colón"},
  {value: 'CVE', label: "Cape Verdean Escudo"},
  {value: 'CZK', label: "Czech Republic Koruna"},
  {value: 'DJF', label: "Djiboutian Franc"},
  {value: 'DKK', label: "Danish Krone"},
  {value: 'DOP', label: "Dominican Peso"},
  {value: 'DZD', label: "Algerian Dinar"},
  {value: 'EEK', label: "Estonian Kroon"},
  {value: 'EGP', label: "Egyptian Pound"},
  {value: 'ERN', label: "Eritrean Nakfa"},
  {value: 'ETB', label: "Ethiopian Birr"},
  {value: 'GBP', label: "British Pound Sterling"},
  {value: 'GEL', label: "Georgian Lari"},
  {value: 'GHS', label: "Ghanaian Cedi"},
  {value: 'GNF', label: "Guinean Franc"},
  {value: 'GTQ', label: "Guatemalan Quetzal"},
  {value: 'HKD', label: "Hong Kong Dollar"},
  {value: 'HNL', label: "Honduran Lempira"},
  {value: 'HRK', label: "Croatian Kuna"},
  {value: 'HUF', label: "Hungarian Forint"},
  {value: 'IDR', label: "Indonesian Rupiah"},
  {value: 'ILS', label: "Israeli New Sheqel"},
  {value: 'INR', label: "Indian Rupee"},
  {value: 'IQD', label: "Iraqi Dinar"},
  {value: 'IRR', label: "Iranian Rial"},
  {value: 'ISK', label: "Icelandic Króna"},
  {value: 'JMD', label: "Jamaican Dollar"},
  {value: 'JOD', label: "Jordanian Dinar"},
  {value: 'JPY', label: "Japanese Yen"},
  {value: 'KES', label: "Kenyan Shilling"},
  {value: 'KHR', label: "Cambodian Riel"},
  {value: 'KMF', label: "Comorian Franc"},
  {value: 'KRW', label: "South Korean Won"},
  {value: 'KWD', label: "Kuwaiti Dinar"},
  {value: 'KZT', label: "Kazakhstani Tenge"},
  {value: 'LBP', label: "Lebanese Pound"},
  {value: 'LKR', label: "Sri Lankan Rupee"},
  {value: 'LTL', label: "Lithuanian Litas"},
  {value: 'LVL', label: "Latvian Lats"},
  {value: 'LYD', label: "Libyan Dinar"},
  {value: 'MAD', label: "Moroccan Dirham"},
  {value: 'MDL', label: "Moldovan Leu"},
  {value: 'MGA', label: "Malagasy Ariary"},
  {value: 'MKD', label: "Macedonian Denar"},
  {value: 'MMK', label: "Myanma Kyat"},
  {value: 'MOP', label: "Macanese Pataca"},
  {value: 'MUR', label: "Mauritian Rupee"},
  {value: 'MXN', label: "Mexican Peso"},
  {value: 'MYR', label: "Malaysian Ringgit"},
  {value: 'MZN', label: "Mozambican Metical"},
  {value: 'NAD', label: "Namibian Dollar"},
  {value: 'NGN', label: "Nigerian Naira"},
  {value: 'NIO', label: "Nicaraguan Córdoba"},
  {value: 'NOK', label: "Norwegian Krone"},
  {value: 'NPR', label: "Nepalese Rupee"},
  {value: 'NZD', label: "New Zealand Dollar"},
  {value: 'OMR', label: "Omani Rial"},
  {value: 'PAB', label: "Panamanian Balboa"},
  {value: 'PEN', label: "Peruvian Nuevo Sol"},
  {value: 'PHP', label: "Philippine Peso"},
  {value: 'PKR', label: "Pakistani Rupee"},
  {value: 'PLN', label: "Polish Zloty"},
  {value: 'PYG', label: "Paraguayan Guarani"},
  {value: 'QAR', label: "Qatari Rial"},
  {value: 'RON', label: "Romanian Leu"},
  {value: 'RSD', label: "Serbian Dinar"},
  {value: 'RUB', label: "Russian Ruble"},
  {value: 'RWF', label: "Rwandan Franc"},
  {value: 'SAR', label: "Saudi Riyal"},
  {value: 'SDG', label: "Sudanese Pound"},
  {value: 'SEK', label: "Swedish Krona"},
  {value: 'SGD', label: "Singapore Dollar"},
  {value: 'SOS', label: "Somali Shilling"},
  {value: 'SYP', label: "Syrian Pound"},
  {value: 'THB', label: "Thai Baht"},
  {value: 'TND', label: "Tunisian Dinar"},
  {value: 'TOP', label: "Tongan Paʻanga"},
  {value: 'TRY', label: "Turkish Lira"},
  {value: 'TTD', label: "Trinidad and Tobago Dollar"},
  {value: 'TWD', label: "New Taiwan Dollar"},
  {value: 'TZS', label: "Tanzanian Shilling"},
  {value: 'UAH', label: "Ukrainian Hryvnia"},
  {value: 'UGX', label: "Ugandan Shilling"},
  {value: 'UYU', label: "Uruguayan Peso"},
  {value: 'UZS', label: "Uzbekistan Som"},
  {value: 'VEF', label: "Venezuelan Bolívar"},
  {value: 'VND', label: "Vietnamese Dong"},
  {value: 'XAF', label: "CFA Franc BEAC"},
  {value: 'XOF', label: "CFA Franc BCEAO"},
  {value: 'YER', label: "Yemeni Rial"},
  {value: 'ZAR', label: "South African Rand"}
  ]


module.exports = options
